from calibrations.core.calibration_taskflow_task import CalibrationTaskRegistry
import calibrations.data_pullers.data_pull
import calibrations.feature_builders.feature_builder
import calibrations.feature_builders.feature_builder_multi_param
import calibrations.feature_builders.digitizer
import calibrations.views_in_market_trading.market_views_calibration_classes
import calibrations.views_in_market_trading.market_views_merge
#import calibrations.experimental.news_momentum_merge
import calibrations.experimental.feature_importance_experiment
import calibrations.fundamental_rebalancing_trader.fundamental_calibration_classes
import calibrations.jump_recovery_trading.jump_recovery_calibration_classes
import calibrations.basket_pair_trading.basket_pair_trading_calibration_classes
import calibrations.common.interval_builders
import calibrations.quantamental_ml.quantamental_ml

if __name__=="__main__":
    print(len(CalibrationTaskRegistry.registered_classes))
    print(CalibrationTaskRegistry.registered_classes)