name: assetx-calibration
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3=1.4.7
  - botocore=1.7.40
  - dask=1.1.4
  - h5py=2.7.0
  - hdf5=1.10.1
  - jinja2=2.11.3
  - jupyter=1.0.0
  - luigi=2.7.1
  - pandas=0.23.4
  - pandas-datareader=0.8.1
  - pip=19.3.1
  - psutil=5.2.2
  - pykalman=0.9.5
  - pyopenssl=22.0.0
  - pytables=3.4.3
  - python=3.6.10
  - python-graphviz
  - quandl=3.2.0
  - requests=2.27.1
  - s3transfer=0.1.13
  - sqlalchemy=1.1.13
  - sqlite=3.38.2
  - statsmodels=0.9.0
  - tblib=1.7.0
  - urllib3=1.26.8
  - pip:

      - docker==2.5.1
      - docker-pycreds==0.4.0
      - envkey==1.2.5
      - fix-yahoo-finance==0.0.19
      - fredapi==0.4.0
      - google-api-core==1.25.1
      - google-api-python-client==2.2.0
      - google-auth==1.28.1
      - google-auth-httplib2==0.1.0
      - google-cloud-bigquery==2.13.1
      - google-cloud-bigquery-storage==2.2.1
      - google-cloud-core==1.6.0
      - google-cloud-monitoring==2.2.1
      - google-cloud-pubsub==2.4.1
      - google-cloud-storage==1.37.1
      - google-crc32c==1.3.0
      - google-resumable-media==1.3.3
      - googleapis-common-protos==1.56.3
      - gunicorn==19.10.0
      - keras==2.6.0
      - lightgbm==2.2.3
      - multitasking==0.0.11
      - numpy==1.15.4
      - psycopg2==2.9.6
      - pyarrow==1.0.1
      - pybigquery==0.6.1
      - pyhocon==0.3.37
      - pylru==1.0.9
      - pymysql==1.0.2
      - python-levenshtein==0.12.0
      - scikit-learn==0.21.3
      - scipy==1.1.0
      - ta-lib==0.4.17
      - taskflow==2.17.0
      - toposort==1.5
      - yfinance==0.2.18
      - zipline==0.7.0
