name: assetx-calibration-short
channels:
  - conda-forge
  - defaults
dependencies:

  - h5py=2.7.0
  - hdf5=1.10.1
  - pandas=0.23.4
  - pandas-datareader=0.8.1
  - pip=19.3.1
  - python=3.6.10
  - quandl=3.2.0
  - requests=2.27.1
  - statsmodels=0.9.0
  - pip:

      - docker==2.5.1
      - envkey==1.2.5
      - fix-yahoo-finance==0.0.19
      - fredapi==0.4.0
      - google-api-python-client==2.2.0
      - google-cloud-bigquery==2.13.1
      - google-cloud-bigquery-storage==2.2.1
      - google-cloud-core==1.6.0
      - google-cloud-storage==1.37.1
      - gunicorn==19.10.0
      - numpy==1.15.4
      - psycopg2==2.9.6
      - pymysql==1.0.2
      - scikit-learn==0.21.3
      - scipy==1.1.0
      #- ta-lib==0.4.17
      - yfinance==0.2.18
      - zipline==0.7.0
      - python-dotenv
      - pylru==1.0.9
