steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/actions/checkout', '.']
    id: 'checkout'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud -q auth activate-service-account --key-file=${_SA_KEY}
    id: 'auth'
    env:
      - 'SA_KEY=${_SERVICE_ACCOUNT_KEY}' # Provide the service account key as a substitution variable

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r dags/* gs://us-east4-airflowcomposer-d2353cf2-bucket/dags
    id: 'upload-folder'

  # Example of using the output
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Uploaded files: ${UPLOADED_FILES}"
    id: 'print-uploaded-files'
    env:
      - 'UPLOADED_FILES=$(_FILES)' # Use a substitution variable to access the uploaded files from previous step
options:
  logging: CLOUD_LOGGING_ONLY