steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud -q auth activate-service-account --key-file=${_SA_KEY}
    id: 'auth'
    env:
      - 'SA_KEY=${_SERVICE_ACCOUNT_KEY}' # Provide the service account key as a substitution variable

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r dags/* gs://us-east4-airflowcomposer-d2353cf2-bucket/dags/
    id: 'upload-folder'

options:
  logging: CLOUD_LOGGING_ONLY
