steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/calibrationdag:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/calibrationdag:$COMMIT_SHA']
  - name: 'gcr.io/$PROJECT_ID/helm'
    args:
      - 'repo'
      - 'add'
      - 'apache-airflow'
      - 'https://airflow.apache.org'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'kms'
      - 'decrypt'
      - '--ciphertext-file=secrets.yaml.enc'
      - '--plaintext-file=secrets.yaml'
      - '--location=global'
      - '--keyring=abc-keyring-$_ENVIRONMENT'
      - '--key=abc-webshop-$_ENVIRONMENT'
    dir: 'k8s/charts-values/gcloud-sqlproxy/$_VALUES_DIRECTORY'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '$_CLUSTER_ID'
      - '--zone=global'
  - name: 'gcr.io/$PROJECT_ID/helm'
    args:
      - 'upgrade'
      - 'airflow'
      - 'apache-airflow/airflow'
      - '-f'
      - 'k8s/values.yml'
      - '--set'
      - 'images.airflow.repository=gcr.io/$PROJECT_ID/calibrationdag'
      - '--set'
      - 'images.airflow.tag=$COMMIT_SHA'
      - '--wait'
      - '--timeout=15m'
      - '--set'
      - 'ingress.annotations.kubernetes.io/tls-acme="true"'
      - '--atomic'
      - '--namespace'
      - 'default'
options:
  logging: GCS_ONLY
