steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/calibrationdag:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/calibrationdag:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'instance'
      - '--container-image'
      - 'gcr.io/$PROJECT_ID/$IMAGE:$COMMIT_SHA'
  - name: 'gcr.io/$PROJECT_ID/helm'
    args:
      - 'upgrade'
      - 'airflow'
      - 'apache-airflow/airflow'
      - '-f'
      - 'k8s/values.yml'
      - '--set'
      - 'images.airflow.repository=gcr.io/$PROJECT_ID/calibrationdag'
      - '--set'
      - 'images.airflow.tag=$COMMIT_SHA'
      - '--wait'
      - '--timeout=15m'
options:
  logging: GCS_ONLY
