steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud -q auth activate-service-account --key-file=${_SA_KEY}
    id: 'auth'
    env:
      - 'SA_KEY=${_SERVICE_ACCOUNT_KEY}' # Provide the service account key as a substitution variable

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r dags/* gs://us-east4-airflowcomposer-d2353cf2-bucket/dags/
        gsutil -m cp -r plugins/* gs://us-east4-airflowcomposer-d2353cf2-bucket/plugins/
    id: 'upload-folders'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts print-settings python --project=dcm-dev --repository=python-repo --location=us-east4
    id: 'print-settings'

  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m pip install -U twine pip wheel setuptools 
        python -m pip download -r requirements-light.txt -d dist
        twine upload --repository-url https://us-east4-python.pkg.dev/dcm-dev-9fe8/python-repo/ dist/*
    id: 'upload-to-artifact-registry'
    env:
      - PIP_ROOT_USER_ACTION=ignore

#artifacts:
#  objects:
#    location: 'gs://us-east4-python.pkg.dev/dcm-dev-9fe8/python-repo/'
#    paths: ['dist/*']


options:
  logging: CLOUD_LOGGING_ONLY
