steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud -q auth activate-service-account --key-file=${_SA_KEY}
    id: 'auth'
    env:
      - 'SA_KEY=${_SERVICE_ACCOUNT_KEY}' # Provide the service account key as a substitution variable

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r dags/* gs://us-east4-airflowcomposer-d2353cf2-bucket/dags/
    id: 'upload-dag-folder'

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r plugins/* gs://us-east4-airflowcomposer-d2353cf2-bucket/plugins/
    id: 'upload-plugins-folder'

  - name: 'python:3.8.17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install twine
        mkdir dist
        pip download -r requirements.txt -d dist
        twine upload --repository-url=https://us-central1-python.pkg.dev/dcm-dev-9fe8/python-repo/ dist/*
    id: 'upload-to-artifact-registry'

options:
  logging: CLOUD_LOGGING_ONLY
